version: '3.8'
services:
  movies:
    image: hari809/paytmmovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: hari809/paytmtrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: hari809/paytmdth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: hari809/paytmrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
